{% set python_min = '3.10.0' %}
{% set name = "peak-finder-app" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 926956a113b9af644a6a599bfad166ba228683dff98b86abbce6282765ceac5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<3.11
    - dask-core 2022.10.*
    - distributed 2022.10.*
    - numpy >=1.23.5,<1.24.0
    - plotly >=5.19.0,<5.20.0
    - scipy >=1.10.1,<1.11.0
    - tqdm >=4.66.1,<5.0.0
    - geoh5py >=0.9.0,<0.10.0
    - geoapps-utils >=0.3.0,<0.4.0
    - curve-apps >=0.1.0,<0.2.0
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0
    - pydantic >=2.5.2,<2.6.0
    - scikit-image >=0.20.0,<0.21.0
    - tifffile 2024.2.12
  run_constrained:
    - dash >=2.12.0,<3.0.0
    - dash-daq >=0.5.0,<0.6.0
    - flask >=3.0.3,<4.0.0
    - pyqtwebengine >=5.15.2,<5.15.7
    - pyside2 >=5.15.2,<5.16.0
    - pyqt5-qt5 5.15.2
    - pyqtwebengine-qt5 5.15.2

test:
  imports:
    - peak_finder
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Peak Finder App'
  description: |
    Peak-finder-app is a package for the detection and grouping of time-domain electromagnetic 
    (TEM) anomalies measured along flight lines.
  license: MIT
  license_file: 
    - LICENSE
  doc_url: https://mirageoscience-peak-finder-app.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/peak-finder-app

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
