schema_version: 1

context:
  name: peak-finder-app
  version: 0.2.0
  python_min: 3.10
  python_max: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: df8e5a1ab0e14d79df7dc849bad9c1f7d698d405209f58db8f24553a6f49560a

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }},<${{ python_max }}
    # Mira packages
    - geoh5py >=0.10.0,<0.11.dev
    - geoapps-utils >=0.4.0,<0.5.dev
    - curve-apps >=0.2.0,<0.3.dev
    # other direct dependencies
    - dask-core >=2024.6,<2024.7.dev
    - distributed >=2024.6,<2024.7.dev
    - numpy >=1.26.0,<1.27.dev
    - plotly >=5.19.0,<5.20.dev
    - scipy >=1.14.0,<1.15.dev
    - tqdm >=4.66.1,<5.0.0
  run_constraints:
    - dash >=2.12.0,<3.0.dev
    - dash-daq >=0.5.0,<0.6.dev
    - flask >=3.0.3,<4.0.dev
    - pyqtwebengine >=5.15.2,<5.15.7
    - pyside2 >=5.15.2,<5.16.dev

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - peak_finder
      pip_check: true
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
        - dash >=2.12.0,<3.0.dev
        - dash-daq >=0.5.0,<0.6.dev
        - flask >=3.0.3,<4.0.dev
        - pyqtwebengine >=5.15.2,<5.15.7
        - pyside2 >=5.15.2,<5.16.dev
    files:
      source:
        - tests/

about:
  summary: Peak Finder App
  description: |
    Peak-finder-app is a package for the detection and grouping of time-domain electromagnetic
    (TEM) anomalies measured along flight lines.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/peak-finder-app
  documentation: https://mirageoscience-peak-finder-app.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
